import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Login
    documentCreation: 'Document creation with AI power',
    smartDocuments: 'Smart Documents',
    zetaAI: 'ZETA AI',
    proTools: 'Pro Tools',
    cloudSync: 'Cloud Sync',
    continueWithGoogle: 'Continue with Google',
    termsAgree: 'By continuing, you agree to our Terms of Service',
    
    // Dashboard
    searchDocuments: 'Search documents...',
    searchNotes: 'Search notes...',
    searchMedia: 'Search posts...',
    deleteNotebook: 'Delete notebook',
    newDocument: 'New Document',
    documents: 'Documents',
    notes: 'Notes',
    quickNote: 'Quick note...',
    justNow: 'Just now',
    hoursAgo: 'h ago',
    daysAgo: 'd ago',
    noNotesYet: 'No notes yet. Add a quick note below!',
    
    // Editor
    back: 'Back',
    forward: 'Forward',
    save: 'Save',
    saving: 'Saving...',
    search: 'Search',
    allPages: 'All Pages',
    askZeta: 'Ask ZETA...',
    askZetaAnything: 'Ask ZETA anything!',
    brainstormResearch: 'Brainstorm, research, analyze...',
    tools: 'Tools',
    canvas: 'Canvas',
    pagesAI: 'Pages & AI',
    pages: 'pages',
    characters: 'chars',
    
    // Settings
    cloudStorage: 'Cloud Storage',
    logout: 'Logout',
    language: 'Language',
    settings: 'Settings',
    
    // Tools
    select: 'Select',
    pencil: 'Pencil',
    brush: 'Brush',
    crop: 'Crop',
    eraser: 'Eraser',
    circle: 'Circle',
    rectangle: 'Rectangle',
    image: 'Image',
    text: 'Text',
    textSize: 'Text Size',
    pageSize: 'Page Size',
    addPage: 'Add Page',
    voice: 'Voice',
    triangle: 'Triangle',
    square: 'Square',
    star: 'Star',
    font: 'Font',
    colorPicker: 'Color Picker',
    layers: 'Layers',
    pan: 'Hand',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    share: 'Share',
    download: 'Download',
    bold: 'Bold',
    italic: 'Italic',
    alignLeft: 'Align Left',
    alignCenter: 'Align Center',
    alignRight: 'Align Right',
    aiImage: 'AI Image',
    delete: 'Delete',
    penTool: 'Pen',
    translate: 'Translate',
    lineSpacing: 'Line Spacing',
    wordType: 'Text Style',
    marking: 'Highlighter',
    paragraph: 'Paragraph',
    graphic: 'Chart',
    pageColor: 'Page Color',
    zoom: 'Zoom',
    export: 'Export',
    alignJustify: 'Justify',
    shortcuts: 'Shortcuts',
    table: 'Table',
    layers: 'Layers',
    ruler: 'Ruler',
    grid: 'Grid',
    templates: 'Templates',
    qrcode: 'QR Code',
    watermark: 'Watermark',
    pageNumbers: 'Page Numbers',
    headerFooter: 'Header/Footer',
    findReplace: 'Find & Replace',
    words: 'words',
    ring: 'Ring',
    indent: 'Indent',
    margins: 'Margins',
    redact: 'Redact',
    highlighter: 'Highlighter',
    importPdf: 'Import PDF',
    connected: 'Connected',
    connectDrive: 'Connect Drive',
    
    // Subscription
    subscription: 'Subscription',
    choosePlan: 'Choose Your Plan',
    planDescription: 'Unlock powerful features with ZET Mindshare Premium',
    subscriptionNote: 'All plans include 7-day free trial. Cancel anytime.',
    selectPlan: 'Select Plan',
    recommended: 'RECOMMENDED',
    fastSelect: 'Fast Select',
    selected: 'selected',
    monthly: 'Monthly',
    yearly: 'Yearly',
    saveYearly: 'Save per year',
    setReminder: 'Set a reminder to get notified',
    currentPlan: 'Current Plan',

    // Settings tabs
    general: 'General',
    aiSettings: 'AI Settings',
    ranks: 'Ranks',
    questMap: 'Quest Map',
    buyCredits: 'Buy Credits',
    logoutBtn: 'Log Out',

    // Settings content
    profile: 'Profile',
    edit: 'Edit',
    plan: 'Plan',
    cancelSubscription: 'Cancel Subscription',
    openAISettings: 'Open AI Settings',
    currentBadge: 'Current',
    viewPlans: 'View Plans',
    viewCreditPackages: 'View Credit Packages',
    editShortcuts: 'Edit Shortcuts',
    fastSelectActive: 'Active:',
    editFastSelect: 'Edit Fast Select',

    // Notebooks & Notes
    newNotebook: 'New Notebook',
    notebookNamePlaceholder: 'Notebook name...',
    searchInNotebook: 'Search in this notebook...',
    addNoteToNotebook: 'Add note to this notebook...',
    noNotesInNotebook: 'No notes in this notebook',
    notesCount: 'notes',
    reminder: 'Reminder',

    // Documents
    document: 'Document',
    editPDF: 'Edit PDF',
    openPDF: 'Open & Edit PDF',
    clickToUpload: 'Click to upload PDF',
    createDocument: 'Create Document',

    // Delete confirmation
    deleteNote: 'Delete note',
    cannotUndo: 'This action cannot be undone.',
    cancel: 'Cancel',
    yesDelete: 'Yes, delete',

    // Note menu
    noteMenuDelete: 'Delete',
    noteMenuEdit: 'Edit',
    noteMenuCopy: 'Copy',
    noteMenuSendDown: 'Send to bottom',
    noteMenuSendUp: 'Bring to top',
    noteMenuPin: 'Pin',
    noteMenuUnpin: 'Unpin',
    zetaSummary: 'Zeta Summary',
    analyzing: 'Analyzing...',
  },
  tr: {
    // Login
    documentCreation: 'AI destekli belge oluşturma',
    smartDocuments: 'Akıllı Belgeler',
    zetaAI: 'ZETA AI',
    proTools: 'Pro Araçlar',
    cloudSync: 'Bulut Senkron',
    continueWithGoogle: 'Google ile Devam Et',
    termsAgree: 'Devam ederek Kullanım Şartlarını kabul etmiş olursunuz',
    
    // Dashboard
    searchDocuments: 'Belge ara...',
    searchNotes: 'Not ara...',
    searchMedia: 'Gönderi ara...',
    deleteNotebook: 'Defteri sil',
    newDocument: 'Yeni Belge',
    documents: 'Belgeler',
    notes: 'Notlar',
    quickNote: 'Hızlı not...',
    justNow: 'Az önce',
    hoursAgo: 's önce',
    daysAgo: 'g önce',
    noNotesYet: 'Henüz not yok. Aşağıdan hızlı not ekleyin!',
    
    // Editor
    back: 'Geri',
    forward: 'İleri',
    save: 'Kaydet',
    saving: 'Kaydediliyor...',
    search: 'Ara',
    allPages: 'Tüm Sayfalar',
    askZeta: 'ZETA\'ya sor...',
    askZetaAnything: 'ZETA\'ya her şeyi sor!',
    brainstormResearch: 'Beyin fırtınası, araştırma, analiz...',
    tools: 'Araçlar',
    canvas: 'Tuval',
    pagesAI: 'Sayfalar & AI',
    pages: 'sayfa',
    characters: 'karakter',
    
    // Settings
    cloudStorage: 'Bulut Depolama',
    logout: 'Çıkış',
    language: 'Dil',
    settings: 'Ayarlar',
    
    // Tools
    select: 'Seç',
    pencil: 'Kalem',
    brush: 'Fırça',
    crop: 'Kırp',
    eraser: 'Silgi',
    circle: 'Daire',
    rectangle: 'Dikdörtgen',
    image: 'Resim',
    text: 'Metin',
    textSize: 'Metin Boyutu',
    pageSize: 'Sayfa Boyutu',
    addPage: 'Sayfa Ekle',
    voice: 'Ses',
    triangle: 'Üçgen',
    square: 'Kare',
    star: 'Yıldız',
    font: 'Yazı Tipi',
    colorPicker: 'Renk Seçici',
    layers: 'Katmanlar',
    pan: 'El',
    zoomIn: 'Yakınlaştır',
    zoomOut: 'Uzaklaştır',
    share: 'Paylaş',
    download: 'İndir',
    bold: 'Kalın',
    italic: 'İtalik',
    alignLeft: 'Sola Hizala',
    alignCenter: 'Ortala',
    alignRight: 'Sağa Hizala',
    aiImage: 'AI Görsel',
    delete: 'Sil',
    penTool: 'Kalem (Vektörel)',
    translate: 'Çevir',
    lineSpacing: 'Satır Aralığı',
    wordType: 'Yazı Tipi',
    marking: 'Fosforlu Kalem',
    paragraph: 'Paragraf',
    graphic: 'Grafik',
    pageColor: 'Sayfa Rengi',
    zoom: 'Büyüteç',
    export: 'Dışa Aktar',
    alignJustify: 'İki Yana Yasla',
    shortcuts: 'Kısayollar',
    table: 'Tablo',
    layers: 'Katmanlar',
    ruler: 'Cetvel',
    grid: 'Izgara',
    templates: 'Şablonlar',
    qrcode: 'QR Kod',
    watermark: 'Filigran',
    pageNumbers: 'Sayfa Numaraları',
    headerFooter: 'Üstbilgi/Altbilgi',
    findReplace: 'Bul ve Değiştir',
    words: 'kelime',
    ring: 'Halka',
    indent: 'Girinti',
    margins: 'Kenar Boşlukları',
    redact: 'Sansür',
    highlighter: 'İşaretleyici',
    importPdf: 'PDF İçe Aktar',
    connected: 'Bağlı',
    connectDrive: 'Drive Bağla',
    
    // Subscription
    subscription: 'Abonelik',
    choosePlan: 'Planınızı Seçin',
    planDescription: 'ZET Mindshare Premium ile güçlü özelliklerin kilidini açın',
    subscriptionNote: 'Tüm planlar 7 günlük ücretsiz deneme içerir. İstediğiniz zaman iptal edin.',
    selectPlan: 'Planı Seç',
    recommended: 'ÖNERİLEN',
    fastSelect: 'Hızlı Seçim',
    selected: 'seçildi',
    monthly: 'Aylık',
    yearly: 'Yıllık',
    saveYearly: 'Yılda tasarruf edin',
    setReminder: 'Bildirim almak için hatırlatıcı ayarlayın',
    currentPlan: 'Mevcut Plan',

    // Settings tabs
    general: 'Genel',
    aiSettings: 'AI Ayarları',
    ranks: 'Rütbeler',
    questMap: 'Görev Haritası',
    buyCredits: 'Kredi Al',
    logoutBtn: 'Çıkış Yap',

    // Settings content
    profile: 'Profil',
    edit: 'Düzenle',
    plan: 'Plan',
    cancelSubscription: 'Aboneliği İptal Et',
    openAISettings: 'AI Ayarlarını Aç',
    currentBadge: 'Şu an',
    viewPlans: 'Planları Görüntüle',
    viewCreditPackages: 'Kredi Paketlerini Gör',
    editShortcuts: 'Kısayolları Düzenle',
    fastSelectActive: 'Aktif:',
    editFastSelect: "Fast Select'i Düzenle",

    // Notebooks & Notes
    newNotebook: 'Yeni Defter',
    notebookNamePlaceholder: 'Defter adı...',
    searchInNotebook: 'Bu defterde ara...',
    addNoteToNotebook: 'Bu deftere not ekle...',
    noNotesInNotebook: 'Bu defterde henüz not yok',
    notesCount: 'not',
    reminder: 'Hatırlatıcı',

    // Documents
    document: 'Belge',
    editPDF: 'PDF Düzenle',
    openPDF: 'PDF Aç ve Düzenle',
    clickToUpload: 'PDF yüklemek için tıklayın',
    createDocument: 'Belge Oluştur',

    // Delete confirmation
    deleteNote: 'Notu sil',
    cannotUndo: 'Bu işlem geri alınamaz.',
    cancel: 'İptal',
    yesDelete: 'Evet, sil',

    // Note menu
    noteMenuDelete: 'Sil',
    noteMenuEdit: 'Düzenle',
    noteMenuCopy: 'Kopyala',
    noteMenuSendDown: 'Alta gönder',
    noteMenuSendUp: 'Üste çıkar',
    noteMenuPin: 'Sabitle',
    noteMenuUnpin: 'Sabiti kaldır',
    zetaSummary: 'Zeta Özet',
    analyzing: 'Analiz ediliyor...',
  },
  de: {
    documentCreation: 'Dokumenterstellung mit KI-Power',
    smartDocuments: 'Intelligente Dokumente',
    zetaAI: 'ZETA KI',
    proTools: 'Profi-Werkzeuge',
    cloudSync: 'Cloud-Synchronisierung',
    continueWithGoogle: 'Mit Google fortfahren',
    searchDocuments: 'Dokumente suchen...',
    newDocument: 'Neues Dokument',
    documents: 'Dokumente',
    notes: 'Notizen',
    save: 'Speichern',
    export: 'Exportieren',
    settings: 'Einstellungen',
    logout: 'Abmelden',
    subscription: 'Abonnement',
    choosePlan: 'Wählen Sie Ihren Plan',
    selectPlan: 'Plan auswählen',
    monthly: 'Monatlich',
    yearly: 'Jährlich',
  },
  fr: {
    documentCreation: 'Création de documents avec IA',
    smartDocuments: 'Documents intelligents',
    zetaAI: 'ZETA IA',
    proTools: 'Outils Pro',
    cloudSync: 'Synchronisation Cloud',
    continueWithGoogle: 'Continuer avec Google',
    searchDocuments: 'Rechercher des documents...',
    newDocument: 'Nouveau document',
    documents: 'Documents',
    notes: 'Notes',
    save: 'Enregistrer',
    export: 'Exporter',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    subscription: 'Abonnement',
    choosePlan: 'Choisissez votre plan',
    selectPlan: 'Sélectionner le plan',
    monthly: 'Mensuel',
    yearly: 'Annuel',
  },
  es: {
    documentCreation: 'Creación de documentos con IA',
    smartDocuments: 'Documentos inteligentes',
    zetaAI: 'ZETA IA',
    proTools: 'Herramientas Pro',
    cloudSync: 'Sincronización en la nube',
    continueWithGoogle: 'Continuar con Google',
    searchDocuments: 'Buscar documentos...',
    newDocument: 'Nuevo documento',
    documents: 'Documentos',
    notes: 'Notas',
    save: 'Guardar',
    export: 'Exportar',
    settings: 'Configuración',
    logout: 'Cerrar sesión',
    subscription: 'Suscripción',
    choosePlan: 'Elige tu plan',
    selectPlan: 'Seleccionar plan',
    monthly: 'Mensual',
    yearly: 'Anual',
  },
  ar: {
    documentCreation: 'إنشاء المستندات بقوة الذكاء الاصطناعي',
    smartDocuments: 'مستندات ذكية',
    zetaAI: 'زيتا AI',
    proTools: 'أدوات احترافية',
    cloudSync: 'مزامنة سحابية',
    continueWithGoogle: 'المتابعة مع Google',
    searchDocuments: 'البحث في المستندات...',
    newDocument: 'مستند جديد',
    documents: 'المستندات',
    notes: 'الملاحظات',
    save: 'حفظ',
    export: 'تصدير',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    subscription: 'الاشتراك',
    choosePlan: 'اختر خطتك',
    selectPlan: 'اختر الخطة',
    monthly: 'شهري',
    yearly: 'سنوي',
  },
  ru: {
    documentCreation: 'Создание документов с помощью ИИ',
    smartDocuments: 'Умные документы',
    zetaAI: 'ЗЕТА ИИ',
    proTools: 'Профессиональные инструменты',
    cloudSync: 'Облачная синхронизация',
    continueWithGoogle: 'Продолжить с Google',
    searchDocuments: 'Поиск документов...',
    newDocument: 'Новый документ',
    documents: 'Документы',
    notes: 'Заметки',
    save: 'Сохранить',
    export: 'Экспорт',
    settings: 'Настройки',
    logout: 'Выйти',
    subscription: 'Подписка',
    choosePlan: 'Выберите план',
    selectPlan: 'Выбрать план',
    monthly: 'Ежемесячно',
    yearly: 'Ежегодно',
  },
  ja: {
    documentCreation: 'AIによるドキュメント作成',
    smartDocuments: 'スマートドキュメント',
    zetaAI: 'ZETA AI',
    proTools: 'プロツール',
    cloudSync: 'クラウド同期',
    continueWithGoogle: 'Googleで続ける',
    searchDocuments: 'ドキュメントを検索...',
    newDocument: '新規ドキュメント',
    documents: 'ドキュメント',
    notes: 'メモ',
    save: '保存',
    export: 'エクスポート',
    settings: '設定',
    logout: 'ログアウト',
    subscription: 'サブスクリプション',
    choosePlan: 'プランを選択',
    selectPlan: 'プランを選ぶ',
    monthly: '月額',
    yearly: '年額',
  },
  ko: {
    documentCreation: 'AI 기반 문서 작성',
    smartDocuments: '스마트 문서',
    zetaAI: 'ZETA AI',
    proTools: '프로 도구',
    cloudSync: '클라우드 동기화',
    continueWithGoogle: 'Google로 계속',
    searchDocuments: '문서 검색...',
    newDocument: '새 문서',
    documents: '문서',
    notes: '메모',
    save: '저장',
    export: '내보내기',
    settings: '설정',
    logout: '로그아웃',
    subscription: '구독',
    choosePlan: '플랜 선택',
    selectPlan: '플랜 선택하기',
    monthly: '월간',
    yearly: '연간',
  },
  zh: {
    documentCreation: 'AI驱动的文档创建',
    smartDocuments: '智能文档',
    zetaAI: 'ZETA AI',
    proTools: '专业工具',
    cloudSync: '云同步',
    continueWithGoogle: '使用Google继续',
    searchDocuments: '搜索文档...',
    newDocument: '新建文档',
    documents: '文档',
    notes: '笔记',
    save: '保存',
    export: '导出',
    settings: '设置',
    logout: '退出',
    subscription: '订阅',
    choosePlan: '选择您的计划',
    selectPlan: '选择计划',
    monthly: '月付',
    yearly: '年付',
  }
};

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('zet-language') || 'tr';
  });

  useEffect(() => {
    localStorage.setItem('zet-language', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  const changeLanguage = (lang) => {
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};
