import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Login
    documentCreation: 'Document creation with AI power',
    smartDocuments: 'Smart Documents',
    zetaAI: 'ZETA AI',
    proTools: 'Pro Tools',
    cloudSync: 'Cloud Sync',
    continueWithGoogle: 'Continue with Google',
    termsAgree: 'By continuing, you agree to our Terms of Service',

    // Dashboard
    searchDocuments: 'Search documents...',
    searchNotes: 'Search notes...',
    searchMedia: 'Search posts...',
    deleteNotebook: 'Delete notebook',
    newDocument: 'New Document',
    documents: 'Documents',
    notes: 'Notes',
    quickNote: 'Quick note...',
    justNow: 'Just now',
    hoursAgo: 'h ago',
    daysAgo: 'd ago',
    noNotesYet: 'No notes yet. Add a quick note below!',

    // Editor
    back: 'Back',
    forward: 'Forward',
    save: 'Save',
    saving: 'Saving...',
    search: 'Search',
    allPages: 'All Pages',
    askZeta: 'Ask ZETA...',
    askZetaAnything: 'Ask ZETA anything!',
    brainstormResearch: 'Brainstorm, research, analyze...',
    tools: 'Tools',
    canvas: 'Canvas',
    pagesAI: 'Pages & AI',
    pages: 'pages',
    characters: 'chars',

    // Settings
    cloudStorage: 'Cloud Storage',
    logout: 'Logout',
    language: 'Language',
    settings: 'Settings',

    // Tools
    select: 'Select',
    pencil: 'Pencil',
    brush: 'Brush',
    crop: 'Crop',
    eraser: 'Eraser',
    circle: 'Circle',
    rectangle: 'Rectangle',
    image: 'Image',
    text: 'Text',
    textSize: 'Text Size',
    pageSize: 'Page Size',
    addPage: 'Add Page',
    voice: 'Voice',
    triangle: 'Triangle',
    square: 'Square',
    star: 'Star',
    font: 'Font',
    colorPicker: 'Color Picker',
    layers: 'Layers',
    pan: 'Hand',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    share: 'Share',
    download: 'Download',
    bold: 'Bold',
    italic: 'Italic',
    alignLeft: 'Align Left',
    alignCenter: 'Align Center',
    alignRight: 'Align Right',
    aiImage: 'AI Image',
    delete: 'Delete',
    penTool: 'Pen',
    translate: 'Translate',
    lineSpacing: 'Line Spacing',
    wordType: 'Text Style',
    marking: 'Highlighter',
    paragraph: 'Paragraph',
    graphic: 'Chart',
    pageColor: 'Page Color',
    zoom: 'Zoom',
    export: 'Export',
    alignJustify: 'Justify',
    shortcuts: 'Shortcuts',
    table: 'Table',
    ruler: 'Ruler',
    grid: 'Grid',
    templates: 'Templates',
    qrcode: 'QR Code',
    watermark: 'Watermark',
    pageNumbers: 'Page Numbers',
    headerFooter: 'Header/Footer',
    findReplace: 'Find & Replace',
    calculator: 'Calculator',
    words: 'words',
    ring: 'Ring',
    indent: 'Indent',
    margins: 'Margins',
    columns: 'Columns',
    redact: 'Redact',
    highlighter: 'Highlighter',
    importPdf: 'Import PDF',
    connected: 'Connected',
    connectDrive: 'Connect Drive',
    bulletList: 'Bullet List',
    numberedList: 'Numbered List',
    paragraphStyles: 'Paragraph Styles',
    photoEdit: 'Photo Edit',
    signature: 'Signature',
    copy: 'Copy',
    mirror: 'Mirror',
    emoji: 'Emoji',
    voiceInput: 'Voice Input',
    shapes: 'Shapes',
    punctuation: 'Punctuation',
    zoomTool: 'Zoom',
    link: 'Link',
    mindmap: 'Mind Map',

    // Subscription
    subscription: 'Subscription',
    choosePlan: 'Choose Your Plan',
    planDescription: 'Unlock powerful features with ZET Mindshare Premium',
    subscriptionNote: 'Subscription renews on the same calendar day each month. Cancel anytime.',
    selectPlan: 'Select Plan',
    recommended: 'RECOMMENDED',
    fastSelect: 'Fast Select',
    selected: 'selected',
    monthly: 'Monthly',
    yearly: 'Yearly',
    saveYearly: 'Save per year',
    setReminder: 'Set a reminder to get notified',
    currentPlan: 'Current Plan',

    // Settings tabs
    general: 'General',
    aiSettings: 'AI Settings',
    ranks: 'Ranks',
    questMap: 'Quest Map',
    buyCredits: 'Buy Credits',
    logoutBtn: 'Log Out',

    // Settings content
    profile: 'Profile',
    edit: 'Edit',
    plan: 'Plan',
    cancelSubscription: 'Cancel Subscription',
    openAISettings: 'Open AI Settings',
    currentBadge: 'Current',
    viewPlans: 'View Plans',
    viewCreditPackages: 'View Credit Packages',
    editShortcuts: 'Edit Shortcuts',
    fastSelectActive: 'Active:',
    editFastSelect: 'Edit Fast Select',

    // Notebooks & Notes
    newNotebook: 'New Notebook',
    notebookNamePlaceholder: 'Notebook name...',
    searchInNotebook: 'Search in this notebook...',
    addNoteToNotebook: 'Add note to this notebook...',
    noNotesInNotebook: 'No notes in this notebook',
    notesCount: 'notes',
    reminder: 'Reminder',

    // Documents
    document: 'Document',
    editPDF: 'Edit PDF',
    openPDF: 'Open & Edit PDF',
    clickToUpload: 'Click to upload PDF',
    createDocument: 'Create Document',

    // Delete confirmation
    deleteNote: 'Delete note',
    cannotUndo: 'This action cannot be undone.',
    cancel: 'Cancel',
    yesDelete: 'Yes, delete',

    // Note menu
    noteMenuDelete: 'Delete',
    noteMenuEdit: 'Edit',
    noteMenuCopy: 'Copy',
    noteMenuSendDown: 'Send to bottom',
    noteMenuSendUp: 'Bring to top',
    noteMenuPin: 'Pin',
    noteMenuUnpin: 'Unpin',
    zetaSummary: 'Zeta Summary',
    analyzing: 'Analyzing...',
  },
  tr: {
    // Login
    documentCreation: 'AI destekli belge oluşturma',
    smartDocuments: 'Akıllı Belgeler',
    zetaAI: 'ZETA AI',
    proTools: 'Pro Araçlar',
    cloudSync: 'Bulut Senkron',
    continueWithGoogle: 'Google ile Devam Et',
    termsAgree: 'Devam ederek Kullanım Şartlarını kabul etmiş olursunuz',

    // Dashboard
    searchDocuments: 'Belge ara...',
    searchNotes: 'Not ara...',
    searchMedia: 'Gönderi ara...',
    deleteNotebook: 'Defteri sil',
    newDocument: 'Yeni Belge',
    documents: 'Belgeler',
    notes: 'Notlar',
    quickNote: 'Hızlı not...',
    justNow: 'Az önce',
    hoursAgo: 's önce',
    daysAgo: 'g önce',
    noNotesYet: 'Henüz not yok. Aşağıdan hızlı not ekleyin!',

    // Editor
    back: 'Geri',
    forward: 'İleri',
    save: 'Kaydet',
    saving: 'Kaydediliyor...',
    search: 'Ara',
    allPages: 'Tüm Sayfalar',
    askZeta: 'ZETA\'ya sor...',
    askZetaAnything: 'ZETA\'ya her şeyi sor!',
    brainstormResearch: 'Beyin fırtınası, araştırma, analiz...',
    tools: 'Araçlar',
    canvas: 'Tuval',
    pagesAI: 'Sayfalar & AI',
    pages: 'sayfa',
    characters: 'karakter',

    // Settings
    cloudStorage: 'Bulut Depolama',
    logout: 'Çıkış',
    language: 'Dil',
    settings: 'Ayarlar',

    // Tools
    select: 'Seç',
    pencil: 'Kalem',
    brush: 'Fırça',
    crop: 'Kırp',
    eraser: 'Silgi',
    circle: 'Daire',
    rectangle: 'Dikdörtgen',
    image: 'Resim',
    text: 'Metin',
    textSize: 'Metin Boyutu',
    pageSize: 'Sayfa Boyutu',
    addPage: 'Sayfa Ekle',
    voice: 'Ses',
    triangle: 'Üçgen',
    square: 'Kare',
    star: 'Yıldız',
    font: 'Yazı Tipi',
    colorPicker: 'Renk Seçici',
    layers: 'Katmanlar',
    pan: 'El',
    zoomIn: 'Yakınlaştır',
    zoomOut: 'Uzaklaştır',
    share: 'Paylaş',
    download: 'İndir',
    bold: 'Kalın',
    italic: 'İtalik',
    alignLeft: 'Sola Hizala',
    alignCenter: 'Ortala',
    alignRight: 'Sağa Hizala',
    aiImage: 'AI Görsel',
    delete: 'Sil',
    penTool: 'Kalem (Vektörel)',
    translate: 'Çevir',
    lineSpacing: 'Satır Aralığı',
    wordType: 'Yazı Tipi',
    marking: 'Fosforlu Kalem',
    paragraph: 'Paragraf',
    graphic: 'Grafik',
    pageColor: 'Sayfa Rengi',
    zoom: 'Büyüteç',
    export: 'Dışa Aktar',
    alignJustify: 'İki Yana Yasla',
    shortcuts: 'Kısayollar',
    table: 'Tablo',
    ruler: 'Cetvel',
    grid: 'Izgara',
    templates: 'Şablonlar',
    qrcode: 'QR Kod',
    watermark: 'Filigran',
    pageNumbers: 'Sayfa Numaraları',
    headerFooter: 'Üstbilgi/Altbilgi',
    findReplace: 'Bul ve Değiştir',
    calculator: 'Hesap Makinesi',
    words: 'kelime',
    ring: 'Halka',
    indent: 'Girinti',
    margins: 'Kenar Boşlukları',
    columns: 'Sütun Düzeni',
    redact: 'Sansür',
    highlighter: 'İşaretleyici',
    importPdf: 'PDF İçe Aktar',
    connected: 'Bağlı',
    connectDrive: 'Drive Bağla',
    bulletList: 'Madde İmi',
    numberedList: 'Numaralı Liste',
    paragraphStyles: 'Paragraf Stilleri',
    photoEdit: 'Fotoğraf Düzenleme',
    signature: 'İmza',
    copy: 'Kopyala',
    mirror: 'Ayna',
    emoji: 'Emoji',
    voiceInput: 'Ses Girişi',
    shapes: 'Şekiller',
    punctuation: 'Noktalama',
    zoomTool: 'Zoom',
    link: 'Bağlantı',
    mindmap: 'Zihin Haritası',

    // Subscription
    subscription: 'Abonelik',
    choosePlan: 'Planınızı Seçin',
    planDescription: 'ZET Mindshare Premium ile güçlü özelliklerin kilidini açın',
    subscriptionNote: 'Abonelik aynı takvim günü her ay yenilenir. İstediğiniz zaman iptal edebilirsiniz.',
    selectPlan: 'Planı Seç',
    recommended: 'ÖNERİLEN',
    fastSelect: 'Hızlı Seçim',
    selected: 'seçildi',
    monthly: 'Aylık',
    yearly: 'Yıllık',
    saveYearly: 'Yılda tasarruf edin',
    setReminder: 'Bildirim almak için hatırlatıcı ayarlayın',
    currentPlan: 'Mevcut Plan',

    // Settings tabs
    general: 'Genel',
    aiSettings: 'AI Ayarları',
    ranks: 'Rütbeler',
    questMap: 'Görev Haritası',
    buyCredits: 'Kredi Al',
    logoutBtn: 'Çıkış Yap',

    // Settings content
    profile: 'Profil',
    edit: 'Düzenle',
    plan: 'Plan',
    cancelSubscription: 'Aboneliği İptal Et',
    openAISettings: 'AI Ayarlarını Aç',
    currentBadge: 'Şu an',
    viewPlans: 'Planları Görüntüle',
    viewCreditPackages: 'Kredi Paketlerini Gör',
    editShortcuts: 'Kısayolları Düzenle',
    fastSelectActive: 'Aktif:',
    editFastSelect: "Fast Select'i Düzenle",

    // Notebooks & Notes
    newNotebook: 'Yeni Defter',
    notebookNamePlaceholder: 'Defter adı...',
    searchInNotebook: 'Bu defterde ara...',
    addNoteToNotebook: 'Bu deftere not ekle...',
    noNotesInNotebook: 'Bu defterde henüz not yok',
    notesCount: 'not',
    reminder: 'Hatırlatıcı',

    // Documents
    document: 'Belge',
    editPDF: 'PDF Düzenle',
    openPDF: 'PDF Aç ve Düzenle',
    clickToUpload: 'PDF yüklemek için tıklayın',
    createDocument: 'Belge Oluştur',

    // Delete confirmation
    deleteNote: 'Notu sil',
    cannotUndo: 'Bu işlem geri alınamaz.',
    cancel: 'İptal',
    yesDelete: 'Evet, sil',

    // Note menu
    noteMenuDelete: 'Sil',
    noteMenuEdit: 'Düzenle',
    noteMenuCopy: 'Kopyala',
    noteMenuSendDown: 'Alta gönder',
    noteMenuSendUp: 'Üste çıkar',
    noteMenuPin: 'Sabitle',
    noteMenuUnpin: 'Sabiti kaldır',
    zetaSummary: 'Zeta Özet',
    analyzing: 'Analiz ediliyor...',
  },
  de: {
    documentCreation: 'Dokumenterstellung mit KI-Power',
    smartDocuments: 'Intelligente Dokumente',
    zetaAI: 'ZETA KI',
    proTools: 'Profi-Werkzeuge',
    cloudSync: 'Cloud-Synchronisierung',
    continueWithGoogle: 'Mit Google fortfahren',
    termsAgree: 'Mit dem Fortfahren stimmen Sie unseren Nutzungsbedingungen zu',
    searchDocuments: 'Dokumente suchen...',
    searchNotes: 'Notizen suchen...',
    searchMedia: 'Beiträge suchen...',
    deleteNotebook: 'Notizbuch löschen',
    newDocument: 'Neues Dokument',
    documents: 'Dokumente',
    notes: 'Notizen',
    quickNote: 'Schnelle Notiz...',
    justNow: 'Gerade eben',
    hoursAgo: 'Std. vor',
    daysAgo: 'T. vor',
    noNotesYet: 'Noch keine Notizen. Fügen Sie unten eine schnelle Notiz hinzu!',
    back: 'Zurück',
    forward: 'Vorwärts',
    save: 'Speichern',
    saving: 'Wird gespeichert...',
    search: 'Suchen',
    allPages: 'Alle Seiten',
    askZeta: 'ZETA fragen...',
    askZetaAnything: 'Frag ZETA alles!',
    brainstormResearch: 'Brainstormen, recherchieren, analysieren...',
    tools: 'Werkzeuge',
    canvas: 'Leinwand',
    pagesAI: 'Seiten & KI',
    pages: 'Seiten',
    characters: 'Zeichen',
    cloudStorage: 'Cloud-Speicher',
    logout: 'Abmelden',
    language: 'Sprache',
    settings: 'Einstellungen',
    select: 'Auswählen',
    pencil: 'Bleistift',
    brush: 'Pinsel',
    crop: 'Zuschneiden',
    eraser: 'Radierer',
    circle: 'Kreis',
    rectangle: 'Rechteck',
    image: 'Bild',
    text: 'Text',
    textSize: 'Textgröße',
    pageSize: 'Seitenformat',
    addPage: 'Seite hinzufügen',
    voice: 'Stimme',
    triangle: 'Dreieck',
    square: 'Quadrat',
    star: 'Stern',
    font: 'Schriftart',
    colorPicker: 'Farbauswahl',
    layers: 'Ebenen',
    pan: 'Hand',
    zoomIn: 'Vergrößern',
    zoomOut: 'Verkleinern',
    share: 'Teilen',
    download: 'Herunterladen',
    bold: 'Fett',
    italic: 'Kursiv',
    alignLeft: 'Linksbündig',
    alignCenter: 'Zentriert',
    alignRight: 'Rechtsbündig',
    aiImage: 'KI-Bild',
    delete: 'Löschen',
    penTool: 'Stift',
    translate: 'Übersetzen',
    lineSpacing: 'Zeilenabstand',
    wordType: 'Textstil',
    marking: 'Textmarker',
    paragraph: 'Absatz',
    graphic: 'Diagramm',
    pageColor: 'Seitenfarbe',
    zoom: 'Zoom',
    export: 'Exportieren',
    alignJustify: 'Blocksatz',
    shortcuts: 'Tastenkürzel',
    table: 'Tabelle',
    ruler: 'Lineal',
    grid: 'Raster',
    templates: 'Vorlagen',
    qrcode: 'QR-Code',
    watermark: 'Wasserzeichen',
    pageNumbers: 'Seitenzahlen',
    headerFooter: 'Kopf-/Fußzeile',
    findReplace: 'Suchen & Ersetzen',
    calculator: 'Taschenrechner',
    words: 'Wörter',
    ring: 'Ring',
    indent: 'Einzug',
    margins: 'Seitenränder',
    columns: 'Spalten',
    redact: 'Schwärzen',
    highlighter: 'Markierung',
    importPdf: 'PDF importieren',
    connected: 'Verbunden',
    connectDrive: 'Drive verbinden',
    bulletList: 'Aufzählungsliste',
    numberedList: 'Nummerierte Liste',
    paragraphStyles: 'Absatzstile',
    photoEdit: 'Fotobearbeitung',
    signature: 'Signatur',
    copy: 'Kopieren',
    mirror: 'Spiegeln',
    emoji: 'Emoji',
    voiceInput: 'Spracheingabe',
    shapes: 'Formen',
    punctuation: 'Zeichensetzung',
    zoomTool: 'Zoom',
    link: 'Link',
    mindmap: 'Mindmap',
    subscription: 'Abonnement',
    choosePlan: 'Wählen Sie Ihren Plan',
    planDescription: 'Schalten Sie leistungsstarke Funktionen mit ZET Mindshare Premium frei',
    subscriptionNote: 'Das Abonnement verlängert sich jeden Monat am selben Kalendertag. Jederzeit kündbar.',
    selectPlan: 'Plan auswählen',
    recommended: 'EMPFOHLEN',
    fastSelect: 'Schnellauswahl',
    selected: 'ausgewählt',
    monthly: 'Monatlich',
    yearly: 'Jährlich',
    saveYearly: 'Jährlich sparen',
    setReminder: 'Erinnerung setzen, um benachrichtigt zu werden',
    currentPlan: 'Aktueller Plan',
    general: 'Allgemein',
    aiSettings: 'KI-Einstellungen',
    ranks: 'Ränge',
    questMap: 'Quest-Karte',
    buyCredits: 'Credits kaufen',
    logoutBtn: 'Abmelden',
    profile: 'Profil',
    edit: 'Bearbeiten',
    plan: 'Plan',
    cancelSubscription: 'Abonnement kündigen',
    openAISettings: 'KI-Einstellungen öffnen',
    currentBadge: 'Aktuell',
    viewPlans: 'Pläne anzeigen',
    viewCreditPackages: 'Credit-Pakete anzeigen',
    editShortcuts: 'Tastenkürzel bearbeiten',
    fastSelectActive: 'Aktiv:',
    editFastSelect: 'Schnellauswahl bearbeiten',
    newNotebook: 'Neues Notizbuch',
    notebookNamePlaceholder: 'Notizbuchname...',
    searchInNotebook: 'In diesem Notizbuch suchen...',
    addNoteToNotebook: 'Notiz zu diesem Notizbuch hinzufügen...',
    noNotesInNotebook: 'Keine Notizen in diesem Notizbuch',
    notesCount: 'Notizen',
    reminder: 'Erinnerung',
    document: 'Dokument',
    editPDF: 'PDF bearbeiten',
    openPDF: 'PDF öffnen und bearbeiten',
    clickToUpload: 'Zum Hochladen klicken',
    createDocument: 'Dokument erstellen',
    deleteNote: 'Notiz löschen',
    cannotUndo: 'Diese Aktion kann nicht rückgängig gemacht werden.',
    cancel: 'Abbrechen',
    yesDelete: 'Ja, löschen',
    noteMenuDelete: 'Löschen',
    noteMenuEdit: 'Bearbeiten',
    noteMenuCopy: 'Kopieren',
    noteMenuSendDown: 'Nach unten senden',
    noteMenuSendUp: 'Nach oben bringen',
    noteMenuPin: 'Anheften',
    noteMenuUnpin: 'Lösen',
    zetaSummary: 'Zeta Zusammenfassung',
    analyzing: 'Wird analysiert...',
  },
  fr: {
    documentCreation: 'Création de documents avec IA',
    smartDocuments: 'Documents intelligents',
    zetaAI: 'ZETA IA',
    proTools: 'Outils Pro',
    cloudSync: 'Synchronisation Cloud',
    continueWithGoogle: 'Continuer avec Google',
    termsAgree: "En continuant, vous acceptez nos Conditions d'utilisation",
    searchDocuments: 'Rechercher des documents...',
    searchNotes: 'Rechercher des notes...',
    searchMedia: 'Rechercher des publications...',
    deleteNotebook: 'Supprimer le carnet',
    newDocument: 'Nouveau document',
    documents: 'Documents',
    notes: 'Notes',
    quickNote: 'Note rapide...',
    justNow: "À l'instant",
    hoursAgo: 'h il y a',
    daysAgo: 'j il y a',
    noNotesYet: 'Pas encore de notes. Ajoutez une note rapide ci-dessous !',
    back: 'Retour',
    forward: 'Suivant',
    save: 'Enregistrer',
    saving: 'Enregistrement...',
    search: 'Rechercher',
    allPages: 'Toutes les pages',
    askZeta: 'Demander à ZETA...',
    askZetaAnything: 'Demandez tout à ZETA !',
    brainstormResearch: 'Brainstormer, rechercher, analyser...',
    tools: 'Outils',
    canvas: 'Canevas',
    pagesAI: 'Pages & IA',
    pages: 'pages',
    characters: 'car.',
    cloudStorage: 'Stockage Cloud',
    logout: 'Déconnexion',
    language: 'Langue',
    settings: 'Paramètres',
    select: 'Sélectionner',
    pencil: 'Crayon',
    brush: 'Pinceau',
    crop: 'Rogner',
    eraser: 'Gomme',
    circle: 'Cercle',
    rectangle: 'Rectangle',
    image: 'Image',
    text: 'Texte',
    textSize: 'Taille du texte',
    pageSize: 'Format de page',
    addPage: 'Ajouter une page',
    voice: 'Voix',
    triangle: 'Triangle',
    square: 'Carré',
    star: 'Étoile',
    font: 'Police',
    colorPicker: 'Sélecteur de couleur',
    layers: 'Calques',
    pan: 'Main',
    zoomIn: 'Zoom avant',
    zoomOut: 'Zoom arrière',
    share: 'Partager',
    download: 'Télécharger',
    bold: 'Gras',
    italic: 'Italique',
    alignLeft: 'Aligner à gauche',
    alignCenter: 'Centrer',
    alignRight: 'Aligner à droite',
    aiImage: 'Image IA',
    delete: 'Supprimer',
    penTool: 'Stylo',
    translate: 'Traduire',
    lineSpacing: 'Interligne',
    wordType: 'Style de texte',
    marking: 'Surligneur',
    paragraph: 'Paragraphe',
    graphic: 'Graphique',
    pageColor: 'Couleur de page',
    zoom: 'Zoom',
    export: 'Exporter',
    alignJustify: 'Justifier',
    shortcuts: 'Raccourcis',
    table: 'Tableau',
    ruler: 'Règle',
    grid: 'Grille',
    templates: 'Modèles',
    qrcode: 'Code QR',
    watermark: 'Filigrane',
    pageNumbers: 'Numéros de page',
    headerFooter: 'En-tête/Pied de page',
    findReplace: 'Rechercher & Remplacer',
    calculator: 'Calculatrice',
    words: 'mots',
    ring: 'Anneau',
    indent: 'Retrait',
    margins: 'Marges',
    columns: 'Colonnes',
    redact: 'Caviarder',
    highlighter: 'Surlignage',
    importPdf: 'Importer PDF',
    connected: 'Connecté',
    connectDrive: 'Connecter Drive',
    bulletList: 'Liste à puces',
    numberedList: 'Liste numérotée',
    paragraphStyles: 'Styles de paragraphe',
    photoEdit: 'Retouche photo',
    signature: 'Signature',
    copy: 'Copier',
    mirror: 'Miroir',
    emoji: 'Emoji',
    voiceInput: 'Saisie vocale',
    shapes: 'Formes',
    punctuation: 'Ponctuation',
    zoomTool: 'Zoom',
    link: 'Lien',
    mindmap: 'Carte mentale',
    subscription: 'Abonnement',
    choosePlan: 'Choisissez votre plan',
    planDescription: 'Débloquez des fonctionnalités puissantes avec ZET Mindshare Premium',
    subscriptionNote: "L'abonnement se renouvelle le même jour du calendrier chaque mois. Annulez à tout moment.",
    selectPlan: 'Sélectionner le plan',
    recommended: 'RECOMMANDÉ',
    fastSelect: 'Sélection rapide',
    selected: 'sélectionné',
    monthly: 'Mensuel',
    yearly: 'Annuel',
    saveYearly: 'Économiser par an',
    setReminder: 'Définir un rappel pour être notifié',
    currentPlan: 'Plan actuel',
    general: 'Général',
    aiSettings: 'Paramètres IA',
    ranks: 'Grades',
    questMap: 'Carte de quêtes',
    buyCredits: 'Acheter des crédits',
    logoutBtn: 'Se déconnecter',
    profile: 'Profil',
    edit: 'Modifier',
    plan: 'Plan',
    cancelSubscription: "Annuler l'abonnement",
    openAISettings: 'Ouvrir les paramètres IA',
    currentBadge: 'Actuel',
    viewPlans: 'Voir les plans',
    viewCreditPackages: 'Voir les forfaits crédits',
    editShortcuts: 'Modifier les raccourcis',
    fastSelectActive: 'Actif :',
    editFastSelect: 'Modifier la sélection rapide',
    newNotebook: 'Nouveau carnet',
    notebookNamePlaceholder: 'Nom du carnet...',
    searchInNotebook: 'Rechercher dans ce carnet...',
    addNoteToNotebook: 'Ajouter une note à ce carnet...',
    noNotesInNotebook: 'Aucune note dans ce carnet',
    notesCount: 'notes',
    reminder: 'Rappel',
    document: 'Document',
    editPDF: 'Modifier PDF',
    openPDF: 'Ouvrir et modifier PDF',
    clickToUpload: 'Cliquez pour télécharger PDF',
    createDocument: 'Créer un document',
    deleteNote: 'Supprimer la note',
    cannotUndo: 'Cette action est irréversible.',
    cancel: 'Annuler',
    yesDelete: 'Oui, supprimer',
    noteMenuDelete: 'Supprimer',
    noteMenuEdit: 'Modifier',
    noteMenuCopy: 'Copier',
    noteMenuSendDown: 'Envoyer en bas',
    noteMenuSendUp: 'Monter en haut',
    noteMenuPin: 'Épingler',
    noteMenuUnpin: 'Désépingler',
    zetaSummary: 'Résumé Zeta',
    analyzing: 'Analyse en cours...',
  },
  es: {
    documentCreation: 'Creación de documentos con IA',
    smartDocuments: 'Documentos inteligentes',
    zetaAI: 'ZETA IA',
    proTools: 'Herramientas Pro',
    cloudSync: 'Sincronización en la nube',
    continueWithGoogle: 'Continuar con Google',
    termsAgree: 'Al continuar, aceptas nuestros Términos de servicio',
    searchDocuments: 'Buscar documentos...',
    searchNotes: 'Buscar notas...',
    searchMedia: 'Buscar publicaciones...',
    deleteNotebook: 'Eliminar cuaderno',
    newDocument: 'Nuevo documento',
    documents: 'Documentos',
    notes: 'Notas',
    quickNote: 'Nota rápida...',
    justNow: 'Ahora mismo',
    hoursAgo: 'h atrás',
    daysAgo: 'd atrás',
    noNotesYet: 'Aún no hay notas. ¡Añade una nota rápida abajo!',
    back: 'Atrás',
    forward: 'Adelante',
    save: 'Guardar',
    saving: 'Guardando...',
    search: 'Buscar',
    allPages: 'Todas las páginas',
    askZeta: 'Pregunta a ZETA...',
    askZetaAnything: '¡Pregúntale cualquier cosa a ZETA!',
    brainstormResearch: 'Lluvia de ideas, investigar, analizar...',
    tools: 'Herramientas',
    canvas: 'Lienzo',
    pagesAI: 'Páginas e IA',
    pages: 'páginas',
    characters: 'car.',
    cloudStorage: 'Almacenamiento en la nube',
    logout: 'Cerrar sesión',
    language: 'Idioma',
    settings: 'Configuración',
    select: 'Seleccionar',
    pencil: 'Lápiz',
    brush: 'Pincel',
    crop: 'Recortar',
    eraser: 'Borrador',
    circle: 'Círculo',
    rectangle: 'Rectángulo',
    image: 'Imagen',
    text: 'Texto',
    textSize: 'Tamaño de texto',
    pageSize: 'Tamaño de página',
    addPage: 'Añadir página',
    voice: 'Voz',
    triangle: 'Triángulo',
    square: 'Cuadrado',
    star: 'Estrella',
    font: 'Fuente',
    colorPicker: 'Selector de color',
    layers: 'Capas',
    pan: 'Mano',
    zoomIn: 'Acercar',
    zoomOut: 'Alejar',
    share: 'Compartir',
    download: 'Descargar',
    bold: 'Negrita',
    italic: 'Cursiva',
    alignLeft: 'Alinear a la izquierda',
    alignCenter: 'Centrar',
    alignRight: 'Alinear a la derecha',
    aiImage: 'Imagen IA',
    delete: 'Eliminar',
    penTool: 'Pluma',
    translate: 'Traducir',
    lineSpacing: 'Interlineado',
    wordType: 'Estilo de texto',
    marking: 'Resaltador',
    paragraph: 'Párrafo',
    graphic: 'Gráfico',
    pageColor: 'Color de página',
    zoom: 'Zoom',
    export: 'Exportar',
    alignJustify: 'Justificar',
    shortcuts: 'Atajos',
    table: 'Tabla',
    ruler: 'Regla',
    grid: 'Cuadrícula',
    templates: 'Plantillas',
    qrcode: 'Código QR',
    watermark: 'Marca de agua',
    pageNumbers: 'Números de página',
    headerFooter: 'Encabezado/Pie de página',
    findReplace: 'Buscar y reemplazar',
    calculator: 'Calculadora',
    words: 'palabras',
    ring: 'Anillo',
    indent: 'Sangría',
    margins: 'Márgenes',
    columns: 'Columnas',
    redact: 'Redactar',
    highlighter: 'Marcador',
    importPdf: 'Importar PDF',
    connected: 'Conectado',
    connectDrive: 'Conectar Drive',
    bulletList: 'Lista de viñetas',
    numberedList: 'Lista numerada',
    paragraphStyles: 'Estilos de párrafo',
    photoEdit: 'Editar foto',
    signature: 'Firma',
    copy: 'Copiar',
    mirror: 'Espejo',
    emoji: 'Emoji',
    voiceInput: 'Entrada de voz',
    shapes: 'Formas',
    punctuation: 'Puntuación',
    zoomTool: 'Zoom',
    link: 'Enlace',
    mindmap: 'Mapa mental',
    subscription: 'Suscripción',
    choosePlan: 'Elige tu plan',
    planDescription: 'Desbloquea funciones potentes con ZET Mindshare Premium',
    subscriptionNote: 'La suscripción se renueva el mismo día del calendario cada mes. Cancela cuando quieras.',
    selectPlan: 'Seleccionar plan',
    recommended: 'RECOMENDADO',
    fastSelect: 'Selección rápida',
    selected: 'seleccionado',
    monthly: 'Mensual',
    yearly: 'Anual',
    saveYearly: 'Ahorrar por año',
    setReminder: 'Establece un recordatorio para ser notificado',
    currentPlan: 'Plan actual',
    general: 'General',
    aiSettings: 'Configuración IA',
    ranks: 'Rangos',
    questMap: 'Mapa de misiones',
    buyCredits: 'Comprar créditos',
    logoutBtn: 'Cerrar sesión',
    profile: 'Perfil',
    edit: 'Editar',
    plan: 'Plan',
    cancelSubscription: 'Cancelar suscripción',
    openAISettings: 'Abrir configuración IA',
    currentBadge: 'Actual',
    viewPlans: 'Ver planes',
    viewCreditPackages: 'Ver paquetes de créditos',
    editShortcuts: 'Editar atajos',
    fastSelectActive: 'Activo:',
    editFastSelect: 'Editar selección rápida',
    newNotebook: 'Nuevo cuaderno',
    notebookNamePlaceholder: 'Nombre del cuaderno...',
    searchInNotebook: 'Buscar en este cuaderno...',
    addNoteToNotebook: 'Añadir nota a este cuaderno...',
    noNotesInNotebook: 'No hay notas en este cuaderno',
    notesCount: 'notas',
    reminder: 'Recordatorio',
    document: 'Documento',
    editPDF: 'Editar PDF',
    openPDF: 'Abrir y editar PDF',
    clickToUpload: 'Haz clic para subir PDF',
    createDocument: 'Crear documento',
    deleteNote: 'Eliminar nota',
    cannotUndo: 'Esta acción no se puede deshacer.',
    cancel: 'Cancelar',
    yesDelete: 'Sí, eliminar',
    noteMenuDelete: 'Eliminar',
    noteMenuEdit: 'Editar',
    noteMenuCopy: 'Copiar',
    noteMenuSendDown: 'Enviar al final',
    noteMenuSendUp: 'Subir al inicio',
    noteMenuPin: 'Fijar',
    noteMenuUnpin: 'Desfijar',
    zetaSummary: 'Resumen Zeta',
    analyzing: 'Analizando...',
  },
  ar: {
    documentCreation: 'إنشاء المستندات بقوة الذكاء الاصطناعي',
    smartDocuments: 'مستندات ذكية',
    zetaAI: 'زيتا AI',
    proTools: 'أدوات احترافية',
    cloudSync: 'مزامنة سحابية',
    continueWithGoogle: 'المتابعة مع Google',
    termsAgree: 'بالمتابعة، فإنك توافق على شروط الخدمة',
    searchDocuments: 'البحث في المستندات...',
    searchNotes: 'البحث في الملاحظات...',
    searchMedia: 'البحث في المنشورات...',
    deleteNotebook: 'حذف الدفتر',
    newDocument: 'مستند جديد',
    documents: 'المستندات',
    notes: 'الملاحظات',
    quickNote: 'ملاحظة سريعة...',
    justNow: 'الآن',
    hoursAgo: 'س مضت',
    daysAgo: 'ي مضى',
    noNotesYet: 'لا توجد ملاحظات بعد. أضف ملاحظة سريعة أدناه!',
    back: 'رجوع',
    forward: 'للأمام',
    save: 'حفظ',
    saving: 'جاري الحفظ...',
    search: 'بحث',
    allPages: 'جميع الصفحات',
    askZeta: 'اسأل ZETA...',
    askZetaAnything: 'اسأل ZETA أي شيء!',
    brainstormResearch: 'العصف الذهني، البحث، التحليل...',
    tools: 'الأدوات',
    canvas: 'اللوحة',
    pagesAI: 'الصفحات والذكاء الاصطناعي',
    pages: 'صفحات',
    characters: 'أحرف',
    cloudStorage: 'التخزين السحابي',
    logout: 'تسجيل الخروج',
    language: 'اللغة',
    settings: 'الإعدادات',
    select: 'تحديد',
    pencil: 'قلم رصاص',
    brush: 'فرشاة',
    crop: 'قص',
    eraser: 'ممحاة',
    circle: 'دائرة',
    rectangle: 'مستطيل',
    image: 'صورة',
    text: 'نص',
    textSize: 'حجم النص',
    pageSize: 'حجم الصفحة',
    addPage: 'إضافة صفحة',
    voice: 'صوت',
    triangle: 'مثلث',
    square: 'مربع',
    star: 'نجمة',
    font: 'الخط',
    colorPicker: 'منتقي الألوان',
    layers: 'الطبقات',
    pan: 'اليد',
    zoomIn: 'تكبير',
    zoomOut: 'تصغير',
    share: 'مشاركة',
    download: 'تنزيل',
    bold: 'غامق',
    italic: 'مائل',
    alignLeft: 'محاذاة لليسار',
    alignCenter: 'توسيط',
    alignRight: 'محاذاة لليمين',
    aiImage: 'صورة ذكاء اصطناعي',
    delete: 'حذف',
    penTool: 'قلم',
    translate: 'ترجمة',
    lineSpacing: 'تباعد الأسطر',
    wordType: 'نمط النص',
    marking: 'تمييز',
    paragraph: 'فقرة',
    graphic: 'رسم بياني',
    pageColor: 'لون الصفحة',
    zoom: 'تكبير/تصغير',
    export: 'تصدير',
    alignJustify: 'ضبط',
    shortcuts: 'اختصارات',
    table: 'جدول',
    ruler: 'مسطرة',
    grid: 'شبكة',
    templates: 'قوالب',
    qrcode: 'رمز QR',
    watermark: 'علامة مائية',
    pageNumbers: 'أرقام الصفحات',
    headerFooter: 'رأس/تذييل الصفحة',
    findReplace: 'بحث واستبدال',
    calculator: 'آلة حاسبة',
    words: 'كلمات',
    ring: 'حلقة',
    indent: 'مسافة بادئة',
    margins: 'هوامش',
    columns: 'أعمدة',
    redact: 'تنقيح',
    highlighter: 'تمييز',
    importPdf: 'استيراد PDF',
    connected: 'متصل',
    connectDrive: 'ربط Drive',
    bulletList: 'قائمة نقطية',
    numberedList: 'قائمة مرقمة',
    paragraphStyles: 'أنماط الفقرة',
    photoEdit: 'تعديل الصورة',
    signature: 'توقيع',
    copy: 'نسخ',
    mirror: 'عكس',
    emoji: 'إيموجي',
    voiceInput: 'إدخال صوتي',
    shapes: 'أشكال',
    punctuation: 'علامات الترقيم',
    zoomTool: 'تكبير/تصغير',
    link: 'رابط',
    mindmap: 'خريطة ذهنية',
    subscription: 'الاشتراك',
    choosePlan: 'اختر خطتك',
    planDescription: 'افتح ميزات قوية مع ZET Mindshare Premium',
    subscriptionNote: 'يتجدد الاشتراك في نفس اليوم من كل شهر. يمكن الإلغاء في أي وقت.',
    selectPlan: 'اختر الخطة',
    recommended: 'موصى به',
    fastSelect: 'اختيار سريع',
    selected: 'محدد',
    monthly: 'شهري',
    yearly: 'سنوي',
    saveYearly: 'وفر سنويًا',
    setReminder: 'اضبط تذكيرًا لتلقي الإشعارات',
    currentPlan: 'الخطة الحالية',
    general: 'عام',
    aiSettings: 'إعدادات الذكاء الاصطناعي',
    ranks: 'الرتب',
    questMap: 'خريطة المهام',
    buyCredits: 'شراء أرصدة',
    logoutBtn: 'تسجيل الخروج',
    profile: 'الملف الشخصي',
    edit: 'تعديل',
    plan: 'الخطة',
    cancelSubscription: 'إلغاء الاشتراك',
    openAISettings: 'فتح إعدادات الذكاء الاصطناعي',
    currentBadge: 'الحالي',
    viewPlans: 'عرض الخطط',
    viewCreditPackages: 'عرض حزم الأرصدة',
    editShortcuts: 'تعديل الاختصارات',
    fastSelectActive: 'نشط:',
    editFastSelect: 'تعديل الاختيار السريع',
    newNotebook: 'دفتر جديد',
    notebookNamePlaceholder: 'اسم الدفتر...',
    searchInNotebook: 'البحث في هذا الدفتر...',
    addNoteToNotebook: 'إضافة ملاحظة إلى هذا الدفتر...',
    noNotesInNotebook: 'لا توجد ملاحظات في هذا الدفتر',
    notesCount: 'ملاحظات',
    reminder: 'تذكير',
    document: 'مستند',
    editPDF: 'تعديل PDF',
    openPDF: 'فتح وتعديل PDF',
    clickToUpload: 'انقر لرفع PDF',
    createDocument: 'إنشاء مستند',
    deleteNote: 'حذف الملاحظة',
    cannotUndo: 'لا يمكن التراجع عن هذا الإجراء.',
    cancel: 'إلغاء',
    yesDelete: 'نعم، احذف',
    noteMenuDelete: 'حذف',
    noteMenuEdit: 'تعديل',
    noteMenuCopy: 'نسخ',
    noteMenuSendDown: 'إرسال للأسفل',
    noteMenuSendUp: 'إرسال للأعلى',
    noteMenuPin: 'تثبيت',
    noteMenuUnpin: 'إلغاء التثبيت',
    zetaSummary: 'ملخص Zeta',
    analyzing: 'جاري التحليل...',
  },
  ru: {
    documentCreation: 'Создание документов с помощью ИИ',
    smartDocuments: 'Умные документы',
    zetaAI: 'ЗЕТА ИИ',
    proTools: 'Профессиональные инструменты',
    cloudSync: 'Облачная синхронизация',
    continueWithGoogle: 'Продолжить с Google',
    termsAgree: 'Продолжая, вы соглашаетесь с нашими Условиями обслуживания',
    searchDocuments: 'Поиск документов...',
    searchNotes: 'Поиск заметок...',
    searchMedia: 'Поиск публикаций...',
    deleteNotebook: 'Удалить блокнот',
    newDocument: 'Новый документ',
    documents: 'Документы',
    notes: 'Заметки',
    quickNote: 'Быстрая заметка...',
    justNow: 'Только что',
    hoursAgo: 'ч назад',
    daysAgo: 'д назад',
    noNotesYet: 'Заметок пока нет. Добавьте быструю заметку ниже!',
    back: 'Назад',
    forward: 'Вперёд',
    save: 'Сохранить',
    saving: 'Сохранение...',
    search: 'Поиск',
    allPages: 'Все страницы',
    askZeta: 'Спросить ZETA...',
    askZetaAnything: 'Спросите ZETA что угодно!',
    brainstormResearch: 'Мозговой штурм, исследование, анализ...',
    tools: 'Инструменты',
    canvas: 'Холст',
    pagesAI: 'Страницы и ИИ',
    pages: 'страниц',
    characters: 'симв.',
    cloudStorage: 'Облачное хранилище',
    logout: 'Выйти',
    language: 'Язык',
    settings: 'Настройки',
    select: 'Выбрать',
    pencil: 'Карандаш',
    brush: 'Кисть',
    crop: 'Обрезать',
    eraser: 'Ластик',
    circle: 'Круг',
    rectangle: 'Прямоугольник',
    image: 'Изображение',
    text: 'Текст',
    textSize: 'Размер текста',
    pageSize: 'Размер страницы',
    addPage: 'Добавить страницу',
    voice: 'Голос',
    triangle: 'Треугольник',
    square: 'Квадрат',
    star: 'Звезда',
    font: 'Шрифт',
    colorPicker: 'Выбор цвета',
    layers: 'Слои',
    pan: 'Рука',
    zoomIn: 'Увеличить',
    zoomOut: 'Уменьшить',
    share: 'Поделиться',
    download: 'Скачать',
    bold: 'Жирный',
    italic: 'Курсив',
    alignLeft: 'По левому краю',
    alignCenter: 'По центру',
    alignRight: 'По правому краю',
    aiImage: 'Изображение ИИ',
    delete: 'Удалить',
    penTool: 'Перо',
    translate: 'Перевести',
    lineSpacing: 'Межстрочный интервал',
    wordType: 'Стиль текста',
    marking: 'Маркер',
    paragraph: 'Абзац',
    graphic: 'График',
    pageColor: 'Цвет страницы',
    zoom: 'Масштаб',
    export: 'Экспорт',
    alignJustify: 'По ширине',
    shortcuts: 'Горячие клавиши',
    table: 'Таблица',
    ruler: 'Линейка',
    grid: 'Сетка',
    templates: 'Шаблоны',
    qrcode: 'QR-код',
    watermark: 'Водяной знак',
    pageNumbers: 'Номера страниц',
    headerFooter: 'Верхний/Нижний колонтитул',
    findReplace: 'Найти и заменить',
    calculator: 'Калькулятор',
    words: 'слов',
    ring: 'Кольцо',
    indent: 'Отступ',
    margins: 'Поля',
    columns: 'Столбцы',
    redact: 'Скрыть',
    highlighter: 'Выделение',
    importPdf: 'Импорт PDF',
    connected: 'Подключено',
    connectDrive: 'Подключить Drive',
    bulletList: 'Маркированный список',
    numberedList: 'Нумерованный список',
    paragraphStyles: 'Стили абзаца',
    photoEdit: 'Редактирование фото',
    signature: 'Подпись',
    copy: 'Копировать',
    mirror: 'Зеркало',
    emoji: 'Эмодзи',
    voiceInput: 'Голосовой ввод',
    shapes: 'Фигуры',
    punctuation: 'Пунктуация',
    zoomTool: 'Масштаб',
    link: 'Ссылка',
    mindmap: 'Интеллект-карта',
    subscription: 'Подписка',
    choosePlan: 'Выберите план',
    planDescription: 'Откройте мощные функции с ZET Mindshare Premium',
    subscriptionNote: 'Подписка продлевается в тот же календарный день каждый месяц. Отмените в любое время.',
    selectPlan: 'Выбрать план',
    recommended: 'РЕКОМЕНДУЕТСЯ',
    fastSelect: 'Быстрый выбор',
    selected: 'выбрано',
    monthly: 'Ежемесячно',
    yearly: 'Ежегодно',
    saveYearly: 'Экономия в год',
    setReminder: 'Установите напоминание, чтобы получить уведомление',
    currentPlan: 'Текущий план',
    general: 'Общие',
    aiSettings: 'Настройки ИИ',
    ranks: 'Ранги',
    questMap: 'Карта заданий',
    buyCredits: 'Купить кредиты',
    logoutBtn: 'Выйти',
    profile: 'Профиль',
    edit: 'Изменить',
    plan: 'План',
    cancelSubscription: 'Отменить подписку',
    openAISettings: 'Открыть настройки ИИ',
    currentBadge: 'Текущий',
    viewPlans: 'Просмотреть планы',
    viewCreditPackages: 'Просмотреть пакеты кредитов',
    editShortcuts: 'Изменить горячие клавиши',
    fastSelectActive: 'Активный:',
    editFastSelect: 'Изменить быстрый выбор',
    newNotebook: 'Новый блокнот',
    notebookNamePlaceholder: 'Название блокнота...',
    searchInNotebook: 'Поиск в этом блокноте...',
    addNoteToNotebook: 'Добавить заметку в этот блокнот...',
    noNotesInNotebook: 'Заметок в этом блокноте нет',
    notesCount: 'заметок',
    reminder: 'Напоминание',
    document: 'Документ',
    editPDF: 'Редактировать PDF',
    openPDF: 'Открыть и редактировать PDF',
    clickToUpload: 'Нажмите, чтобы загрузить PDF',
    createDocument: 'Создать документ',
    deleteNote: 'Удалить заметку',
    cannotUndo: 'Это действие нельзя отменить.',
    cancel: 'Отмена',
    yesDelete: 'Да, удалить',
    noteMenuDelete: 'Удалить',
    noteMenuEdit: 'Изменить',
    noteMenuCopy: 'Копировать',
    noteMenuSendDown: 'Отправить вниз',
    noteMenuSendUp: 'Поднять наверх',
    noteMenuPin: 'Закрепить',
    noteMenuUnpin: 'Открепить',
    zetaSummary: 'Резюме Zeta',
    analyzing: 'Анализируется...',
  },
  ja: {
    documentCreation: 'AIによるドキュメント作成',
    smartDocuments: 'スマートドキュメント',
    zetaAI: 'ZETA AI',
    proTools: 'プロツール',
    cloudSync: 'クラウド同期',
    continueWithGoogle: 'Googleで続ける',
    termsAgree: '続行することで、利用規約に同意します',
    searchDocuments: 'ドキュメントを検索...',
    searchNotes: 'メモを検索...',
    searchMedia: '投稿を検索...',
    deleteNotebook: 'ノートブックを削除',
    newDocument: '新規ドキュメント',
    documents: 'ドキュメント',
    notes: 'メモ',
    quickNote: 'クイックメモ...',
    justNow: 'たった今',
    hoursAgo: '時間前',
    daysAgo: '日前',
    noNotesYet: 'まだメモがありません。下にクイックメモを追加してください！',
    back: '戻る',
    forward: '進む',
    save: '保存',
    saving: '保存中...',
    search: '検索',
    allPages: 'すべてのページ',
    askZeta: 'ZETAに質問...',
    askZetaAnything: 'ZETAに何でも聞いてください！',
    brainstormResearch: 'ブレインストーミング、調査、分析...',
    tools: 'ツール',
    canvas: 'キャンバス',
    pagesAI: 'ページ & AI',
    pages: 'ページ',
    characters: '文字',
    cloudStorage: 'クラウドストレージ',
    logout: 'ログアウト',
    language: '言語',
    settings: '設定',
    select: '選択',
    pencil: '鉛筆',
    brush: 'ブラシ',
    crop: 'トリミング',
    eraser: '消しゴム',
    circle: '円',
    rectangle: '長方形',
    image: '画像',
    text: 'テキスト',
    textSize: 'テキストサイズ',
    pageSize: 'ページサイズ',
    addPage: 'ページを追加',
    voice: '音声',
    triangle: '三角形',
    square: '正方形',
    star: '星',
    font: 'フォント',
    colorPicker: 'カラーピッカー',
    layers: 'レイヤー',
    pan: '手のひら',
    zoomIn: 'ズームイン',
    zoomOut: 'ズームアウト',
    share: '共有',
    download: 'ダウンロード',
    bold: '太字',
    italic: '斜体',
    alignLeft: '左揃え',
    alignCenter: '中央揃え',
    alignRight: '右揃え',
    aiImage: 'AI画像',
    delete: '削除',
    penTool: 'ペン',
    translate: '翻訳',
    lineSpacing: '行間',
    wordType: 'テキストスタイル',
    marking: 'ハイライト',
    paragraph: '段落',
    graphic: 'グラフ',
    pageColor: 'ページカラー',
    zoom: 'ズーム',
    export: 'エクスポート',
    alignJustify: '両端揃え',
    shortcuts: 'ショートカット',
    table: 'テーブル',
    ruler: '定規',
    grid: 'グリッド',
    templates: 'テンプレート',
    qrcode: 'QRコード',
    watermark: '透かし',
    pageNumbers: 'ページ番号',
    headerFooter: 'ヘッダー/フッター',
    findReplace: '検索と置換',
    calculator: '電卓',
    words: '語',
    ring: 'リング',
    indent: 'インデント',
    margins: '余白',
    columns: '段組み',
    redact: '墨消し',
    highlighter: 'マーカー',
    importPdf: 'PDF読み込み',
    connected: '接続済み',
    connectDrive: 'Driveを接続',
    bulletList: '箇条書きリスト',
    numberedList: '番号付きリスト',
    paragraphStyles: '段落スタイル',
    photoEdit: '写真編集',
    signature: '署名',
    copy: 'コピー',
    mirror: 'ミラー',
    emoji: '絵文字',
    voiceInput: '音声入力',
    shapes: '図形',
    punctuation: '句読点',
    zoomTool: 'ズーム',
    link: 'リンク',
    mindmap: 'マインドマップ',
    subscription: 'サブスクリプション',
    choosePlan: 'プランを選択',
    planDescription: 'ZET Mindshare Premiumで強力な機能を解放する',
    subscriptionNote: 'サブスクリプションは毎月同じ日に更新されます。いつでもキャンセル可能。',
    selectPlan: 'プランを選ぶ',
    recommended: 'おすすめ',
    fastSelect: 'クイック選択',
    selected: '選択済み',
    monthly: '月額',
    yearly: '年額',
    saveYearly: '年間節約',
    setReminder: '通知を受け取るためにリマインダーを設定',
    currentPlan: '現在のプラン',
    general: '一般',
    aiSettings: 'AI設定',
    ranks: 'ランク',
    questMap: 'クエストマップ',
    buyCredits: 'クレジットを購入',
    logoutBtn: 'ログアウト',
    profile: 'プロフィール',
    edit: '編集',
    plan: 'プラン',
    cancelSubscription: 'サブスクリプションをキャンセル',
    openAISettings: 'AI設定を開く',
    currentBadge: '現在',
    viewPlans: 'プランを見る',
    viewCreditPackages: 'クレジットパッケージを見る',
    editShortcuts: 'ショートカットを編集',
    fastSelectActive: 'アクティブ:',
    editFastSelect: 'クイック選択を編集',
    newNotebook: '新しいノートブック',
    notebookNamePlaceholder: 'ノートブック名...',
    searchInNotebook: 'このノートブックで検索...',
    addNoteToNotebook: 'このノートブックにメモを追加...',
    noNotesInNotebook: 'このノートブックにメモはありません',
    notesCount: 'メモ',
    reminder: 'リマインダー',
    document: 'ドキュメント',
    editPDF: 'PDFを編集',
    openPDF: 'PDFを開いて編集',
    clickToUpload: 'PDFをアップロードするにはクリック',
    createDocument: 'ドキュメントを作成',
    deleteNote: 'メモを削除',
    cannotUndo: 'この操作は元に戻せません。',
    cancel: 'キャンセル',
    yesDelete: 'はい、削除します',
    noteMenuDelete: '削除',
    noteMenuEdit: '編集',
    noteMenuCopy: 'コピー',
    noteMenuSendDown: '下に送る',
    noteMenuSendUp: '上に持っていく',
    noteMenuPin: 'ピン留め',
    noteMenuUnpin: 'ピン解除',
    zetaSummary: 'Zetaサマリー',
    analyzing: '分析中...',
  },
  ko: {
    documentCreation: 'AI 기반 문서 작성',
    smartDocuments: '스마트 문서',
    zetaAI: 'ZETA AI',
    proTools: '프로 도구',
    cloudSync: '클라우드 동기화',
    continueWithGoogle: 'Google로 계속',
    termsAgree: '계속함으로써 서비스 이용약관에 동의합니다',
    searchDocuments: '문서 검색...',
    searchNotes: '메모 검색...',
    searchMedia: '게시물 검색...',
    deleteNotebook: '노트북 삭제',
    newDocument: '새 문서',
    documents: '문서',
    notes: '메모',
    quickNote: '빠른 메모...',
    justNow: '방금',
    hoursAgo: '시간 전',
    daysAgo: '일 전',
    noNotesYet: '아직 메모가 없습니다. 아래에 빠른 메모를 추가하세요!',
    back: '뒤로',
    forward: '앞으로',
    save: '저장',
    saving: '저장 중...',
    search: '검색',
    allPages: '모든 페이지',
    askZeta: 'ZETA에게 물어보기...',
    askZetaAnything: 'ZETA에게 무엇이든 물어보세요!',
    brainstormResearch: '브레인스토밍, 연구, 분석...',
    tools: '도구',
    canvas: '캔버스',
    pagesAI: '페이지 & AI',
    pages: '페이지',
    characters: '자',
    cloudStorage: '클라우드 저장소',
    logout: '로그아웃',
    language: '언어',
    settings: '설정',
    select: '선택',
    pencil: '연필',
    brush: '브러시',
    crop: '자르기',
    eraser: '지우개',
    circle: '원',
    rectangle: '직사각형',
    image: '이미지',
    text: '텍스트',
    textSize: '텍스트 크기',
    pageSize: '페이지 크기',
    addPage: '페이지 추가',
    voice: '음성',
    triangle: '삼각형',
    square: '정사각형',
    star: '별',
    font: '글꼴',
    colorPicker: '색상 선택기',
    layers: '레이어',
    pan: '손',
    zoomIn: '확대',
    zoomOut: '축소',
    share: '공유',
    download: '다운로드',
    bold: '굵게',
    italic: '기울임',
    alignLeft: '왼쪽 정렬',
    alignCenter: '가운데 정렬',
    alignRight: '오른쪽 정렬',
    aiImage: 'AI 이미지',
    delete: '삭제',
    penTool: '펜',
    translate: '번역',
    lineSpacing: '줄 간격',
    wordType: '텍스트 스타일',
    marking: '형광펜',
    paragraph: '단락',
    graphic: '차트',
    pageColor: '페이지 색상',
    zoom: '확대/축소',
    export: '내보내기',
    alignJustify: '양쪽 정렬',
    shortcuts: '단축키',
    table: '표',
    ruler: '눈금자',
    grid: '격자',
    templates: '템플릿',
    qrcode: 'QR 코드',
    watermark: '워터마크',
    pageNumbers: '페이지 번호',
    headerFooter: '머리글/바닥글',
    findReplace: '찾기 및 바꾸기',
    calculator: '계산기',
    words: '단어',
    ring: '링',
    indent: '들여쓰기',
    margins: '여백',
    columns: '열',
    redact: '편집',
    highlighter: '형광펜',
    importPdf: 'PDF 가져오기',
    connected: '연결됨',
    connectDrive: 'Drive 연결',
    bulletList: '글머리 기호 목록',
    numberedList: '번호 매기기 목록',
    paragraphStyles: '단락 스타일',
    photoEdit: '사진 편집',
    signature: '서명',
    copy: '복사',
    mirror: '미러',
    emoji: '이모지',
    voiceInput: '음성 입력',
    shapes: '도형',
    punctuation: '구두점',
    zoomTool: '확대/축소',
    link: '링크',
    mindmap: '마인드맵',
    subscription: '구독',
    choosePlan: '플랜 선택',
    planDescription: 'ZET Mindshare Premium으로 강력한 기능을 잠금 해제하세요',
    subscriptionNote: '구독은 매월 같은 날에 갱신됩니다. 언제든지 취소 가능합니다.',
    selectPlan: '플랜 선택하기',
    recommended: '추천',
    fastSelect: '빠른 선택',
    selected: '선택됨',
    monthly: '월간',
    yearly: '연간',
    saveYearly: '연간 절약',
    setReminder: '알림을 받으려면 미리 알림을 설정하세요',
    currentPlan: '현재 플랜',
    general: '일반',
    aiSettings: 'AI 설정',
    ranks: '순위',
    questMap: '퀘스트 맵',
    buyCredits: '크레딧 구매',
    logoutBtn: '로그아웃',
    profile: '프로필',
    edit: '편집',
    plan: '플랜',
    cancelSubscription: '구독 취소',
    openAISettings: 'AI 설정 열기',
    currentBadge: '현재',
    viewPlans: '플랜 보기',
    viewCreditPackages: '크레딧 패키지 보기',
    editShortcuts: '단축키 편집',
    fastSelectActive: '활성:',
    editFastSelect: '빠른 선택 편집',
    newNotebook: '새 노트북',
    notebookNamePlaceholder: '노트북 이름...',
    searchInNotebook: '이 노트북에서 검색...',
    addNoteToNotebook: '이 노트북에 메모 추가...',
    noNotesInNotebook: '이 노트북에 메모가 없습니다',
    notesCount: '메모',
    reminder: '미리 알림',
    document: '문서',
    editPDF: 'PDF 편집',
    openPDF: 'PDF 열기 및 편집',
    clickToUpload: 'PDF를 업로드하려면 클릭',
    createDocument: '문서 만들기',
    deleteNote: '메모 삭제',
    cannotUndo: '이 작업은 취소할 수 없습니다.',
    cancel: '취소',
    yesDelete: '예, 삭제합니다',
    noteMenuDelete: '삭제',
    noteMenuEdit: '편집',
    noteMenuCopy: '복사',
    noteMenuSendDown: '아래로 보내기',
    noteMenuSendUp: '위로 올리기',
    noteMenuPin: '고정',
    noteMenuUnpin: '고정 해제',
    zetaSummary: 'Zeta 요약',
    analyzing: '분석 중...',
  },
  zh: {
    documentCreation: 'AI驱动的文档创建',
    smartDocuments: '智能文档',
    zetaAI: 'ZETA AI',
    proTools: '专业工具',
    cloudSync: '云同步',
    continueWithGoogle: '使用Google继续',
    termsAgree: '继续即表示您同意我们的服务条款',
    searchDocuments: '搜索文档...',
    searchNotes: '搜索笔记...',
    searchMedia: '搜索帖子...',
    deleteNotebook: '删除笔记本',
    newDocument: '新建文档',
    documents: '文档',
    notes: '笔记',
    quickNote: '快速笔记...',
    justNow: '刚刚',
    hoursAgo: '小时前',
    daysAgo: '天前',
    noNotesYet: '暂无笔记。在下方添加快速笔记！',
    back: '返回',
    forward: '前进',
    save: '保存',
    saving: '保存中...',
    search: '搜索',
    allPages: '所有页面',
    askZeta: '向ZETA提问...',
    askZetaAnything: '向ZETA提问任何问题！',
    brainstormResearch: '头脑风暴、研究、分析...',
    tools: '工具',
    canvas: '画布',
    pagesAI: '页面 & AI',
    pages: '页',
    characters: '字',
    cloudStorage: '云存储',
    logout: '退出',
    language: '语言',
    settings: '设置',
    select: '选择',
    pencil: '铅笔',
    brush: '画笔',
    crop: '裁剪',
    eraser: '橡皮擦',
    circle: '圆形',
    rectangle: '矩形',
    image: '图片',
    text: '文本',
    textSize: '文字大小',
    pageSize: '页面大小',
    addPage: '添加页面',
    voice: '语音',
    triangle: '三角形',
    square: '正方形',
    star: '星形',
    font: '字体',
    colorPicker: '颜色选择器',
    layers: '图层',
    pan: '手形',
    zoomIn: '放大',
    zoomOut: '缩小',
    share: '分享',
    download: '下载',
    bold: '粗体',
    italic: '斜体',
    alignLeft: '左对齐',
    alignCenter: '居中',
    alignRight: '右对齐',
    aiImage: 'AI图像',
    delete: '删除',
    penTool: '钢笔',
    translate: '翻译',
    lineSpacing: '行距',
    wordType: '文本样式',
    marking: '荧光笔',
    paragraph: '段落',
    graphic: '图表',
    pageColor: '页面颜色',
    zoom: '缩放',
    export: '导出',
    alignJustify: '两端对齐',
    shortcuts: '快捷键',
    table: '表格',
    ruler: '标尺',
    grid: '网格',
    templates: '模板',
    qrcode: '二维码',
    watermark: '水印',
    pageNumbers: '页码',
    headerFooter: '页眉/页脚',
    findReplace: '查找和替换',
    calculator: '计算器',
    words: '词',
    ring: '环形',
    indent: '缩进',
    margins: '页边距',
    columns: '分栏',
    redact: '涂黑',
    highlighter: '高亮',
    importPdf: '导入PDF',
    connected: '已连接',
    connectDrive: '连接Drive',
    bulletList: '项目符号列表',
    numberedList: '编号列表',
    paragraphStyles: '段落样式',
    photoEdit: '照片编辑',
    signature: '签名',
    copy: '复制',
    mirror: '镜像',
    emoji: '表情符号',
    voiceInput: '语音输入',
    shapes: '形状',
    punctuation: '标点符号',
    zoomTool: '缩放',
    link: '链接',
    mindmap: '思维导图',
    subscription: '订阅',
    choosePlan: '选择您的计划',
    planDescription: '使用ZET Mindshare Premium解锁强大功能',
    subscriptionNote: '订阅在每月同一日历日自动续费。随时可取消。',
    selectPlan: '选择计划',
    recommended: '推荐',
    fastSelect: '快速选择',
    selected: '已选择',
    monthly: '月付',
    yearly: '年付',
    saveYearly: '每年节省',
    setReminder: '设置提醒以获得通知',
    currentPlan: '当前计划',
    general: '常规',
    aiSettings: 'AI设置',
    ranks: '等级',
    questMap: '任务地图',
    buyCredits: '购买积分',
    logoutBtn: '退出登录',
    profile: '个人资料',
    edit: '编辑',
    plan: '计划',
    cancelSubscription: '取消订阅',
    openAISettings: '打开AI设置',
    currentBadge: '当前',
    viewPlans: '查看计划',
    viewCreditPackages: '查看积分套餐',
    editShortcuts: '编辑快捷键',
    fastSelectActive: '活跃:',
    editFastSelect: '编辑快速选择',
    newNotebook: '新建笔记本',
    notebookNamePlaceholder: '笔记本名称...',
    searchInNotebook: '在此笔记本中搜索...',
    addNoteToNotebook: '向此笔记本添加笔记...',
    noNotesInNotebook: '此笔记本中没有笔记',
    notesCount: '笔记',
    reminder: '提醒',
    document: '文档',
    editPDF: '编辑PDF',
    openPDF: '打开并编辑PDF',
    clickToUpload: '点击上传PDF',
    createDocument: '创建文档',
    deleteNote: '删除笔记',
    cannotUndo: '此操作无法撤销。',
    cancel: '取消',
    yesDelete: '是，删除',
    noteMenuDelete: '删除',
    noteMenuEdit: '编辑',
    noteMenuCopy: '复制',
    noteMenuSendDown: '发送到底部',
    noteMenuSendUp: '提到顶部',
    noteMenuPin: '固定',
    noteMenuUnpin: '取消固定',
    zetaSummary: 'Zeta摘要',
    analyzing: '分析中...',
  }
};

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('zet-language') || 'tr';
  });

  useEffect(() => {
    const { savePreference } = require('../lib/preferences');
    savePreference('zet-language', language);
  }, [language]);

  // Auth sonrası server'dan gelen tercih güncellenir
  useEffect(() => {
    const onPrefsLoaded = (e) => {
      if (e.detail['zet-language']) setLanguage(e.detail['zet-language']);
    };
    window.addEventListener('zet:preferences-loaded', onPrefsLoaded);
    return () => window.removeEventListener('zet:preferences-loaded', onPrefsLoaded);
  }, []);

  const t = (key) => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  const changeLanguage = (lang) => {
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};
